# Generated by Django 4.2.2 on 2023-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createnote",
            name="created_at",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
